import JSZip from 'jszip';
import { GeneratedStore, Plan } from './types';

function safe(str: string) { return str.replace(/[<>&]/g, s => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[s]!)); }
function sectionSchema(name: string, blocks = '') { return `{% schema %}{"name":"${name}","settings":[],"blocks":[${blocks}],"presets":[{"name":"${name}"}]}{% endschema %}`; }

export async function createShopifyZip(store: GeneratedStore, plan: Plan) {
  const zip = new JSZip();
  const css = `:root{--bg:${store.palette.background};--surface:${store.palette.surface};--text:${store.palette.text};--muted:${store.palette.muted};--accent:${store.palette.accent};--accent2:${store.palette.accent2}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.page-width{max-width:1180px;margin:0 auto;padding:0 20px}.yo-section{padding:72px 0}.yo-hero{min-height:78vh;display:grid;align-items:center;background:radial-gradient(circle at 20% 10%, color-mix(in srgb,var(--accent) 30%,transparent), transparent 35%),radial-gradient(circle at 80% 20%, color-mix(in srgb,var(--accent2) 20%,transparent), transparent 30%)}.yo-grid{display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center}.yo-eyebrow{color:var(--accent2);text-transform:uppercase;letter-spacing:.14em;font-size:12px;font-weight:800}.yo-title{font-size:clamp(40px,7vw,88px);line-height:.95;margin:14px 0}.yo-copy{font-size:clamp(16px,2vw,20px);line-height:1.65;color:var(--muted)}.yo-btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:999px;padding:15px 22px;background:linear-gradient(135deg,var(--accent),var(--accent2));color:white;font-weight:800;text-decoration:none;box-shadow:0 18px 60px color-mix(in srgb,var(--accent) 32%,transparent)}.yo-card{background:linear-gradient(180deg,color-mix(in srgb,var(--surface) 92%,white 8%),var(--surface));border:1px solid rgba(255,255,255,.12);border-radius:28px;padding:24px;box-shadow:0 24px 90px rgba(0,0,0,.3)}.yo-product-img{width:100%;border-radius:24px;aspect-ratio:1/1;object-fit:cover}.yo-benefits{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.yo-benefit{padding:20px;border-radius:22px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1)}.yo-price{font-size:34px;font-weight:900}.yo-compare{color:var(--muted);text-decoration:line-through}.yo-reviews{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.yo-faq details{border-top:1px solid rgba(255,255,255,.12);padding:18px 0}.yo-faq summary{cursor:pointer;font-weight:800}@media(max-width:780px){.yo-section{padding:48px 0}.yo-grid,.yo-benefits,.yo-reviews{grid-template-columns:1fr;gap:22px}.yo-hero{min-height:auto;padding:52px 0}.yo-title{font-size:44px}.yo-card{border-radius:22px;padding:18px}}`;

  zip.file('layout/theme.liquid', `<!doctype html><html lang="{{ request.locale.iso_code }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ page_title }}</title>{{ content_for_header }}{{ 'yoooko-theme.css' | asset_url | stylesheet_tag }}</head><body><main id="MainContent">{{ content_for_layout }}</main></body></html>`);
  zip.file('assets/yoooko-theme.css', css);
  zip.file('templates/index.json', JSON.stringify({ sections: { hero: { type: 'yoooko-hero' }, benefits: { type: 'yoooko-benefits' }, story: { type: 'yoooko-story' }, reviews: { type: 'yoooko-reviews' }, faq: { type: 'yoooko-faq' } }, order: ['hero','benefits','story','reviews','faq'] }, null, 2));
  zip.file('templates/product.json', JSON.stringify({ sections: { main: { type: 'yoooko-product' }, benefits: { type: 'yoooko-benefits' }, faq: { type: 'yoooko-faq' } }, order: ['main','benefits','faq'] }, null, 2));
  zip.file('templates/collection.json', JSON.stringify({ sections: { main: { type: 'main-collection-product-grid' } }, order: ['main'] }, null, 2));
  zip.file('templates/page.about.json', JSON.stringify({ sections: { main: { type: 'yoooko-page-about' } }, order: ['main'] }, null, 2));
  zip.file('templates/page.faq.json', JSON.stringify({ sections: { main: { type: 'yoooko-faq' } }, order: ['main'] }, null, 2));
  zip.file('templates/page.contact.json', JSON.stringify({ sections: { main: { type: 'yoooko-page-contact' } }, order: ['main'] }, null, 2));
  zip.file('templates/page.policies.json', JSON.stringify({ sections: { main: { type: 'yoooko-page-policies' } }, order: ['main'] }, null, 2));

  const img = store.product.images[0];
  zip.file('sections/yoooko-hero.liquid', `<section class="yo-hero"><div class="page-width yo-grid"><div><p class="yo-eyebrow">${safe(store.niche)} · ${safe(plan)}</p><h1 class="yo-title">${safe(store.home.heroTitle)}</h1><p class="yo-copy">${safe(store.home.heroSubtitle)}</p><a class="yo-btn" href="/products/${safe(store.product.name.toLowerCase().replace(/\s+/g,'-'))}">${safe(store.home.cta)}</a></div><div class="yo-card"><img class="yo-product-img" src="${img}" alt="${safe(store.product.name)}"><h2>${safe(store.product.name)}</h2><p class="yo-copy">${safe(store.product.headline)}</p><p><span class="yo-price">${safe(store.product.price)}</span> <span class="yo-compare">${safe(store.product.compareAt)}</span></p></div></div></section>${sectionSchema('Yoooko Hero')}`);
  zip.file('sections/yoooko-benefits.liquid', `<section class="yo-section"><div class="page-width"><p class="yo-eyebrow">Beneficios</p><h2>Diseñada para convertir en móvil</h2><div class="yo-benefits">${store.home.benefits.map(b=>`<div class="yo-benefit">${safe(b)}</div>`).join('')}</div></div></section>${sectionSchema('Yoooko Benefits')}`);
  zip.file('sections/yoooko-story.liquid', `<section class="yo-section"><div class="page-width yo-grid"><div><p class="yo-eyebrow">Problema</p><h2>${safe(store.home.problem)}</h2></div><div class="yo-card"><p class="yo-eyebrow">Solución</p><p class="yo-copy">${safe(store.home.solution)}</p>${store.home.howItWorks.map(x=>`<p>• ${safe(x)}</p>`).join('')}<a class="yo-btn" href="/checkout">Comprar ahora</a></div></div></section>${sectionSchema('Yoooko Story')}`);
  zip.file('sections/yoooko-product.liquid', `<section class="yo-section"><div class="page-width yo-grid"><div class="yo-card"><img class="yo-product-img" src="${img}" alt="{{ product.title | escape }}"></div><div><p class="yo-eyebrow">Oferta limitada</p><h1 class="yo-title">${safe(store.product.name)}</h1><p class="yo-copy">${safe(store.product.headline)}</p><p><span class="yo-price">${safe(store.product.price)}</span> <span class="yo-compare">${safe(store.product.compareAt)}</span></p>${store.product.bullets.map(b=>`<p>✓ ${safe(b)}</p>`).join('')}<form method="post" action="/cart/add"><input type="hidden" name="id" value="{{ product.selected_or_first_available_variant.id }}"><button class="yo-btn" type="submit">Añadir al carrito</button></form><p class="yo-copy">Pago seguro · Envío rastreado · Garantía incluida</p></div></div></section>${sectionSchema('Yoooko Product')}`);
  zip.file('sections/yoooko-reviews.liquid', `<section class="yo-section"><div class="page-width"><p class="yo-eyebrow">Prueba social</p><h2>Compradores que confiaron</h2><div class="yo-reviews">${store.product.reviews.map(r=>`<div class="yo-card"><strong>${safe(r.name)}</strong><p class="yo-copy">${safe(r.text)}</p></div>`).join('')}</div></div></section>${sectionSchema('Yoooko Reviews')}`);
  zip.file('sections/yoooko-faq.liquid', `<section class="yo-section yo-faq"><div class="page-width"><p class="yo-eyebrow">FAQ</p><h2>Preguntas frecuentes</h2>${store.home.faqs.map(f=>`<details><summary>${safe(f.q)}</summary><p class="yo-copy">${safe(f.a)}</p></details>`).join('')}</div></section>${sectionSchema('Yoooko FAQ')}`);
  zip.file('sections/yoooko-page-about.liquid', `<section class="yo-section"><div class="page-width"><p class="yo-eyebrow">Sobre nosotros</p><h1>${safe(store.brand)}</h1><p class="yo-copy">${safe(store.pages.about)}</p></div></section>${sectionSchema('Yoooko About')}`);
  zip.file('sections/yoooko-page-contact.liquid', `<section class="yo-section"><div class="page-width"><p class="yo-eyebrow">Contacto</p><h1>Contacto</h1><p class="yo-copy">${safe(store.pages.contact)}</p>{% form 'contact' %}<input name="contact[email]" placeholder="Email" style="width:100%;padding:16px;border-radius:14px;margin:8px 0"><textarea name="contact[body]" placeholder="Mensaje" style="width:100%;padding:16px;border-radius:14px;min-height:140px"></textarea><button class="yo-btn" type="submit">Enviar</button>{% endform %}</div></section>${sectionSchema('Yoooko Contact')}`);
  zip.file('sections/yoooko-page-policies.liquid', `<section class="yo-section"><div class="page-width"><p class="yo-eyebrow">Políticas</p><h1>Compra segura</h1>${store.pages.policies.map(p=>`<p class="yo-copy">${safe(p)}</p>`).join('')}</div></section>${sectionSchema('Yoooko Policies')}`);
  zip.file('config/settings_schema.json', JSON.stringify([{ name: 'Yoooko Theme', settings: [{ type: 'text', id: 'brand_name', label: 'Nombre de marca', default: store.brand }, { type: 'color', id: 'accent', label: 'Color principal', default: store.palette.accent }] }], null, 2));
  zip.file('locales/es.default.json', JSON.stringify({ general: { accessibility: { skip_to_content: 'Saltar al contenido' } }, products: { product: { add_to_cart: 'Añadir al carrito', sold_out: 'Agotado' } } }, null, 2));
  zip.file('README-YOOOKO.txt', `Tema generado por Yoooko.\nPlan: ${plan}\nIncluye layout, templates JSON, sections Liquid, assets, config y locales.\nSubida: Shopify Admin > Online Store > Themes > Add theme > Upload zip.`);
  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
}
